/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/_blog'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/_blog.index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as StudioLoginRouteImport } from './routes/studio.login'
import { Route as BlogBlogIndexRouteImport } from './routes/_blog.blog.index'
import { Route as BlogBlogIdRouteImport } from './routes/_blog.blog.$id'
import { Route as StudioStudioIndexRouteImport } from './routes/_studio.studio.index'
import { Route as StudioStudioPostsIndexRouteImport } from './routes/_studio.studio.posts.index'
import { Route as StudioStudioPostsUpsertIndexRouteImport } from './routes/_studio.studio.posts.upsert.index'
import { Route as StudioStudioPostsUpsertIdRouteImport } from './routes/_studio.studio.posts.upsert.$id'

const BlogRoute = BlogRouteImport.update({
  id: '/_blog',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/studio/login',
  path: '/studio/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogIndexRoute = BlogBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBlogIdRoute = BlogBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => BlogRoute,
} as any)
const StudioStudioIndexRoute = StudioStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioStudioPostsIndexRoute = StudioStudioPostsIndexRouteImport.update({
  id: '/studio/posts/',
  path: '/studio/posts/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioStudioPostsUpsertIndexRoute =
  StudioStudioPostsUpsertIndexRouteImport.update({
    id: '/studio/posts/upsert/',
    path: '/studio/posts/upsert/',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioStudioPostsUpsertIdRoute =
  StudioStudioPostsUpsertIdRouteImport.update({
    id: '/studio/posts/upsert/$id',
    path: '/studio/posts/upsert/$id',
    getParentRoute: () => StudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof BlogIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/studio/login': typeof StudioLoginRoute
  '/blog/$id': typeof BlogBlogIdRoute
  '/blog/': typeof BlogBlogIndexRoute
  '/studio/': typeof StudioStudioIndexRoute
  '/studio/posts/': typeof StudioStudioPostsIndexRoute
  '/studio/posts/upsert/$id': typeof StudioStudioPostsUpsertIdRoute
  '/studio/posts/upsert/': typeof StudioStudioPostsUpsertIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof BlogIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/studio/login': typeof StudioLoginRoute
  '/blog/$id': typeof BlogBlogIdRoute
  '/blog': typeof BlogBlogIndexRoute
  '/studio': typeof StudioStudioIndexRoute
  '/studio/posts': typeof StudioStudioPostsIndexRoute
  '/studio/posts/upsert/$id': typeof StudioStudioPostsUpsertIdRoute
  '/studio/posts/upsert': typeof StudioStudioPostsUpsertIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_blog': typeof BlogRouteWithChildren
  '/_studio': typeof StudioRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/studio/login': typeof StudioLoginRoute
  '/_blog/': typeof BlogIndexRoute
  '/_blog/blog/$id': typeof BlogBlogIdRoute
  '/_blog/blog/': typeof BlogBlogIndexRoute
  '/_studio/studio/': typeof StudioStudioIndexRoute
  '/_studio/studio/posts/': typeof StudioStudioPostsIndexRoute
  '/_studio/studio/posts/upsert/$id': typeof StudioStudioPostsUpsertIdRoute
  '/_studio/studio/posts/upsert/': typeof StudioStudioPostsUpsertIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/$'
    | '/studio/login'
    | '/blog/$id'
    | '/blog/'
    | '/studio/'
    | '/studio/posts/'
    | '/studio/posts/upsert/$id'
    | '/studio/posts/upsert/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/$'
    | '/studio/login'
    | '/blog/$id'
    | '/blog'
    | '/studio'
    | '/studio/posts'
    | '/studio/posts/upsert/$id'
    | '/studio/posts/upsert'
  id:
    | '__root__'
    | '/_blog'
    | '/_studio'
    | '/sitemap.xml'
    | '/api/$'
    | '/studio/login'
    | '/_blog/'
    | '/_blog/blog/$id'
    | '/_blog/blog/'
    | '/_studio/studio/'
    | '/_studio/studio/posts/'
    | '/_studio/studio/posts/upsert/$id'
    | '/_studio/studio/posts/upsert/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BlogRoute: typeof BlogRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  StudioLoginRoute: typeof StudioLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_blog': {
      id: '/_blog'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blog/': {
      id: '/_blog/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/login': {
      id: '/studio/login'
      path: '/studio/login'
      fullPath: '/studio/login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blog/blog/': {
      id: '/_blog/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogBlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_blog/blog/$id': {
      id: '/_blog/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogBlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_studio/studio/': {
      id: '/_studio/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioStudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/studio/posts/': {
      id: '/_studio/studio/posts/'
      path: '/studio/posts'
      fullPath: '/studio/posts/'
      preLoaderRoute: typeof StudioStudioPostsIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/studio/posts/upsert/': {
      id: '/_studio/studio/posts/upsert/'
      path: '/studio/posts/upsert'
      fullPath: '/studio/posts/upsert/'
      preLoaderRoute: typeof StudioStudioPostsUpsertIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/studio/posts/upsert/$id': {
      id: '/_studio/studio/posts/upsert/$id'
      path: '/studio/posts/upsert/$id'
      fullPath: '/studio/posts/upsert/$id'
      preLoaderRoute: typeof StudioStudioPostsUpsertIdRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogBlogIdRoute: typeof BlogBlogIdRoute
  BlogBlogIndexRoute: typeof BlogBlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogBlogIdRoute: BlogBlogIdRoute,
  BlogBlogIndexRoute: BlogBlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface StudioRouteChildren {
  StudioStudioIndexRoute: typeof StudioStudioIndexRoute
  StudioStudioPostsIndexRoute: typeof StudioStudioPostsIndexRoute
  StudioStudioPostsUpsertIdRoute: typeof StudioStudioPostsUpsertIdRoute
  StudioStudioPostsUpsertIndexRoute: typeof StudioStudioPostsUpsertIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioStudioIndexRoute: StudioStudioIndexRoute,
  StudioStudioPostsIndexRoute: StudioStudioPostsIndexRoute,
  StudioStudioPostsUpsertIdRoute: StudioStudioPostsUpsertIdRoute,
  StudioStudioPostsUpsertIndexRoute: StudioStudioPostsUpsertIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BlogRoute: BlogRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  StudioLoginRoute: StudioLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
