/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as StudioProjectsRouteImport } from './routes/studio/projects'
import { Route as StudioLoginRouteImport } from './routes/studio/login'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as StudioPostsIndexRouteImport } from './routes/studio/posts/index'
import { Route as StudioPostsUpsertIndexRouteImport } from './routes/studio/posts/upsert/index'
import { Route as StudioPostsUpsertIdRouteImport } from './routes/studio/posts/upsert/$id'

const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const StudioProjectsRoute = StudioProjectsRouteImport.update({
  id: '/studio/projects',
  path: '/studio/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/studio/login',
  path: '/studio/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPostsIndexRoute = StudioPostsIndexRouteImport.update({
  id: '/studio/posts/',
  path: '/studio/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPostsUpsertIndexRoute = StudioPostsUpsertIndexRouteImport.update({
  id: '/studio/posts/upsert/',
  path: '/studio/posts/upsert/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPostsUpsertIdRoute = StudioPostsUpsertIdRouteImport.update({
  id: '/studio/posts/upsert/$id',
  path: '/studio/posts/upsert/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/blog/$id': typeof BlogIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/studio/login': typeof StudioLoginRoute
  '/studio/projects': typeof StudioProjectsRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/posts/': typeof StudioPostsIndexRoute
  '/studio/posts/upsert/$id': typeof StudioPostsUpsertIdRoute
  '/studio/posts/upsert/': typeof StudioPostsUpsertIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/blog/$id': typeof BlogIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/studio/login': typeof StudioLoginRoute
  '/studio/projects': typeof StudioProjectsRoute
  '/blog': typeof BlogIndexRoute
  '/studio': typeof StudioIndexRoute
  '/studio/posts': typeof StudioPostsIndexRoute
  '/studio/posts/upsert/$id': typeof StudioPostsUpsertIdRoute
  '/studio/posts/upsert': typeof StudioPostsUpsertIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/blog/$id': typeof BlogIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/studio/login': typeof StudioLoginRoute
  '/studio/projects': typeof StudioProjectsRoute
  '/blog/': typeof BlogIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/posts/': typeof StudioPostsIndexRoute
  '/studio/posts/upsert/$id': typeof StudioPostsUpsertIdRoute
  '/studio/posts/upsert/': typeof StudioPostsUpsertIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/api/$'
    | '/blog/$id'
    | '/sitemap/xml'
    | '/studio/login'
    | '/studio/projects'
    | '/blog/'
    | '/studio/'
    | '/studio/posts/'
    | '/studio/posts/upsert/$id'
    | '/studio/posts/upsert/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/blog/$id'
    | '/sitemap/xml'
    | '/studio/login'
    | '/studio/projects'
    | '/blog'
    | '/studio'
    | '/studio/posts'
    | '/studio/posts/upsert/$id'
    | '/studio/posts/upsert'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/api/$'
    | '/blog/$id'
    | '/sitemap/xml'
    | '/studio/login'
    | '/studio/projects'
    | '/blog/'
    | '/studio/'
    | '/studio/posts/'
    | '/studio/posts/upsert/$id'
    | '/studio/posts/upsert/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  StudioLoginRoute: typeof StudioLoginRoute
  StudioProjectsRoute: typeof StudioProjectsRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioPostsIndexRoute: typeof StudioPostsIndexRoute
  StudioPostsUpsertIdRoute: typeof StudioPostsUpsertIdRoute
  StudioPostsUpsertIndexRoute: typeof StudioPostsUpsertIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/studio/projects': {
      id: '/studio/projects'
      path: '/studio/projects'
      fullPath: '/studio/projects'
      preLoaderRoute: typeof StudioProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/login': {
      id: '/studio/login'
      path: '/studio/login'
      fullPath: '/studio/login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/posts/': {
      id: '/studio/posts/'
      path: '/studio/posts'
      fullPath: '/studio/posts/'
      preLoaderRoute: typeof StudioPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/posts/upsert/': {
      id: '/studio/posts/upsert/'
      path: '/studio/posts/upsert'
      fullPath: '/studio/posts/upsert/'
      preLoaderRoute: typeof StudioPostsUpsertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/posts/upsert/$id': {
      id: '/studio/posts/upsert/$id'
      path: '/studio/posts/upsert/$id'
      fullPath: '/studio/posts/upsert/$id'
      preLoaderRoute: typeof StudioPostsUpsertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogIdRoute: BlogIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  StudioLoginRoute: StudioLoginRoute,
  StudioProjectsRoute: StudioProjectsRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioPostsIndexRoute: StudioPostsIndexRoute,
  StudioPostsUpsertIdRoute: StudioPostsUpsertIdRoute,
  StudioPostsUpsertIndexRoute: StudioPostsUpsertIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
